# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-07 12:06
from __future__ import unicode_literals

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0046_auto_20190216_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='name',
            field=models.CharField(max_length=80, validators=[Core.validators.validate_file_extension]),
        ),
    ]
